import {
  AcademicSessions,
  Report,
  Building1,
  Floor1,
  Room,
  Room1,
  RoomInfo,
  RoomRequest,
  RoomRequestTable,
} from "@/types";
import { removeSpaces } from "@/utils";
import { NextRequest, NextResponse } from "next/server";

export async function POST(request: NextRequest) {
  const response = NextResponse.json;

  console.log(`requested URL ${request.url}`);
  const { searchParams } = new URL(request.url);

  if (
    request.url.includes(
      `${process.env.NEXT_PUBLIC_BASE_URL}${process.env.NEXT_PUBLIC_GET_ACADMIC_YEARS}`
    )
  )
    return response({ "Academic Year": AcademicYears });

  if (
    request.url.includes(
      `${process.env.NEXT_PUBLIC_BASE_URL}${process.env.NEXT_PUBLIC_GET_ACADMIC_SESSIONS}`
    )
  )
    return response({ "Academic Session": AcademicSession });
  if (request.url.includes(`${process.env.NEXT_PUBLIC_GET_BUILDING_LIST}`))
    return response(BuildingsData);
  if (
    request.url.includes(
      `${process.env.NEXT_PUBLIC_BASE_URL}${process.env.NEXT_PUBLIC_GET_REPORTS}`
    )
  ) {
    let res = {
      totalPages: 1,
      currentPage: 1,
      pageSize: 10,
      reports: Reports,
    };
    return response(res);
  }
  if (
    request.url.includes(
      `${process.env.NEXT_PUBLIC_BASE_URL}${process.env.NEXT_PUBLIC_GET_ROOMS_LIST}`
    )
  ) {
    const body = await request.json();
    let buildingId = body["buildingNo"];
    let floorId = body["floorID"];
    return response(
      RoomsData.filter((room) => {
        return buildingId == room.buildingId && floorId == room.floor;
      })
    );
  }
  if (
    request.url.includes(
      `${process.env.NEXT_PUBLIC_BASE_URL}${process.env.NEXT_PUBLIC_GET_SUBROOMS_LIST}`
    )
  ) {
    const body = await request.json();
    let roomId = body["roomId"];
    console.log("roomInfo:  ", roomId);
    return response(
      SubRoomsData.filter((room) => {
        return room.parentId === roomId;
      })
    );
  }
  if (
    request.url.includes(
      `${process.env.NEXT_PUBLIC_BASE_URL}${process.env.NEXT_PUBLIC_GET_REQUEST_LIST}`
    )
  ) {
    const body = await request.json();
    let limit = parseInt(body["limit"]!);
    let offSet = parseInt(body["offset"]!);
    let startIndex = (offSet - 1) * limit;
    let totalPage = Math.ceil(RequestData.requests.length / limit);
    let curruntPage = offSet;
    if (offSet > totalPage) curruntPage = totalPage;

    const reqData = {
      curruntPage: curruntPage,
      totalPages: totalPage,
      pageSize: limit,
      requests: RequestData.requests.slice(startIndex, startIndex + limit),
    };
    return response(reqData);
  }
  if (
    request.url.includes(
      `${process.env.NEXT_PUBLIC_BASE_URL}${process.env.NEXT_PUBLIC_GET_DASHBOARD_DATA}`
    )
  ) {
    const body = await request.json();
    let days = body["noOfDays"];
    if (days === "7") return response(DashboardData7D);
    else return response(DashboardData30D);
  }
  if (
    request.url.includes(
      `${process.env.NEXT_PUBLIC_BASE_URL}${process.env.NEXT_PUBLIC_GET_ROOM_INFO}`
    )
  ) {
    const body = await request.json();
    let roomId = body["roomId"];
    let roomInfo = RoomInformation.filter((room) => room.id === roomId);
    return response(roomInfo[0] || RoomInformation[0]);
  }
  if (
    request.url.includes(
      `${process.env.NEXT_PUBLIC_BASE_URL}${process.env.NEXT_PUBLIC_GET_SEARCH}`
    )
  ) {
    const body = await request.json();
    let searchText = body["searchKey"];
    let buildings = BuildingsData.filter((building) => {
      return removeSpaces(building.name)
        .toLowerCase()
        .includes(searchText!.toLowerCase());
    });
    let rooms = RoomsData.filter((room) => {
      return removeSpaces(room.roomName)
        .toLowerCase()
        .includes(searchText!.toLowerCase());
    });

    let b = buildings.map((item) => {
      return {
        buildingId: item.id,
        name: item.name,
        type: "building",
      };
    });
    let r = rooms.map((item) => {
      return {
        buildingId: item.buildingId,
        name: item.roomName,
        type: "room",
        roomId: item.id,
      };
    });
    let res = {
      buildings: b,
      rooms: r,
    };
    return response(res);
  }
  if (
    request.url.includes(
      `${process.env.NEXT_PUBLIC_BASE_URL}${process.env.NEXT_PUBLIC_GET_USER}`
    )
  ) {
    const user = {
      userId: "Emp003",
      userName: "Lalit Dehraj",
      userContact: "9891135663",
      userDepartment: "CSE",
      userPosition: "Developer",
      activeSession: "Jul-Dec",
      activeYear: "2025-26",
      userImage: "",
    };
    return response(user);
  } else return response({ error: "return from end" });
}
const AcademicYears = [
  {
    Code: "25-26",
    Description: "2025-26",
  },
  {
    Code: "24-25",
    Description: "2024-25",
  },
  {
    Code: "23-24",
    Description: "2023-24",
  },
  {
    Code: "22-23",
    Description: "2022-23",
  },
  {
    Code: "21-22",
    Description: "2021-22",
  },
  {
    Code: "20-21",
    Description: "2020-21",
  },
  {
    Code: "19-20",
    Description: "2019-20",
  },
  {
    Code: "18-19",
    Description: "2018-19",
  },
  {
    Code: "17-18",
    Description: "2017-18",
  },
  {
    Code: "16-17",
    Description: "2016-17",
  },
  {
    Code: "15-16",
    Description: "2015-16",
  },
  {
    Code: "14-15",
    Description: "2014-15",
  },
  {
    Code: "13-14",
    Description: "2013-14",
  },
  {
    Code: "12-13",
    Description: "2012-13",
  },
  {
    Code: "11-12",
    Description: "2011-12",
  },
].reverse();
const AcademicSession = [
  {
    Code: "AUG-NOV 2018",
    "Academic Year": "18-19",
  },
  {
    Code: "AUG-NOV 2019",
    "Academic Year": "19-20",
  },
  {
    Code: "AUG-NOV 2020",
    "Academic Year": "20-21",
  },
  {
    Code: "AUG-NOV 2021",
    "Academic Year": "21-22",
  },
  {
    Code: "AUG-NOV 2022",
    "Academic Year": "22-23",
  },
  {
    Code: "AUG-NOV 2023",
    "Academic Year": "23-24",
  },
  {
    Code: "FEB-APRIL 2019",
    "Academic Year": "18-19",
  },
  {
    Code: "FEB-APRIL 2020",
    "Academic Year": "19-20",
  },
  {
    Code: "FEB-APRIL 2021",
    "Academic Year": "20-21",
  },
  {
    Code: "FEB-APRIL 2022",
    "Academic Year": "21-22",
  },
  {
    Code: "FEB-APRIL 2023",
    "Academic Year": "22-23",
  },
  {
    Code: "FEB-APRIL 2024",
    "Academic Year": "23-24",
  },
  {
    Code: "JAN-MAY 2017",
    "Academic Year": "16-17",
  },
  {
    Code: "JAN-MAY 2018",
    "Academic Year": "17-18",
  },
  {
    Code: "JAN-MAY 2019",
    "Academic Year": "18-19",
  },
  {
    Code: "JAN-MAY 2020",
    "Academic Year": "19-20",
  },
  {
    Code: "JAN-MAY 2021",
    "Academic Year": "20-21",
  },
  {
    Code: "JAN-MAY 2022",
    "Academic Year": "21-22",
  },
  {
    Code: "JAN-MAY 2023",
    "Academic Year": "22-23",
  },
  {
    Code: "JAN-MAY 2024",
    "Academic Year": "23-24",
  },
  {
    Code: "JAN-MAY 2025",
    "Academic Year": "24-25",
  },
  {
    Code: "JUL 2018 - MAY 2019",
    "Academic Year": "18-19",
  },
  {
    Code: "JUL 2019 - MAY 2020",
    "Academic Year": "19-20",
  },
  {
    Code: "JUL 2020 - MAY 2021",
    "Academic Year": "20-21",
  },
  {
    Code: "JUL 2021 - MAY 2022",
    "Academic Year": "21-22",
  },
  {
    Code: "JUL 2022 - MAY 2023",
    "Academic Year": "22-23",
  },
  {
    Code: "JUL 2023 - MAY 2024",
    "Academic Year": "23-24",
  },
  {
    Code: "JUL 2024 - MAY 2025",
    "Academic Year": "24-25",
  },
  {
    Code: "JUL-NOV 2017",
    "Academic Year": "17-18",
  },
  {
    Code: "JUL-NOV 2018",
    "Academic Year": "18-19",
  },
  {
    Code: "JUL-NOV 2019",
    "Academic Year": "19-20",
  },
  {
    Code: "JUL-NOV 2020",
    "Academic Year": "20-21",
  },
  {
    Code: "JUL-NOV 2021",
    "Academic Year": "21-22",
  },
  {
    Code: "JUL-NOV 2022",
    "Academic Year": "22-23",
  },
  {
    Code: "JUL-NOV 2023",
    "Academic Year": "23-24",
  },
  {
    Code: "JUL-NOV 2024",
    "Academic Year": "24-25",
  },
  {
    Code: "NOV-FEB 2019",
    "Academic Year": "18-19",
  },
  {
    Code: "NOV-FEB 2020",
    "Academic Year": "19-20",
  },
  {
    Code: "NOV-FEB 2021",
    "Academic Year": "20-21",
  },
  {
    Code: "NOV-FEB 2022",
    "Academic Year": "21-22",
  },
  {
    Code: "NOV-FEB 2023",
    "Academic Year": "22-23",
  },
  {
    Code: "NOV-FEB 2024",
    "Academic Year": "23-24",
  },
  {
    Code: "SUMMER 2017",
    "Academic Year": "16-17",
  },
  {
    Code: "SUMMER 2018",
    "Academic Year": "17-18",
  },
  {
    Code: "SUMMER 2019",
    "Academic Year": "18-19",
  },
  {
    Code: "SUMMER 2020",
    "Academic Year": "19-20",
  },
  {
    Code: "SUMMER 2021",
    "Academic Year": "20-21",
  },
  {
    Code: "SUMMER 2022",
    "Academic Year": "21-22",
  },
  {
    Code: "SUMMER 2022-I",
    "Academic Year": "21-22",
  },
  {
    Code: "SUMMER 2022-II",
    "Academic Year": "21-22",
  },
  {
    Code: "SUMMER 2023",
    "Academic Year": "22-23",
  },
  {
    Code: "SUMMER 2024",
    "Academic Year": "23-24",
  },
  {
    Code: "SUMMER 2024-I",
    "Academic Year": "23-24",
  },
  {
    Code: "SUMMER 2025",
    "Academic Year": "24-25",
  },
  {
    Code: "WINTER 2019",
    "Academic Year": "19-20",
  },
  {
    Code: "WINTER 2021",
    "Academic Year": "21-22",
  },
  {
    Code: "WINTER 2022",
    "Academic Year": "22-23",
  },
  {
    Code: "WINTER 2023",
    "Academic Year": "23-24",
  },
  {
    Code: "WINTER 2024",
    "Academic Year": "24-25",
  },
  {
    Code: "WINTER 2024-I",
    "Academic Year": "24-25",
  },
];

const BuildingsData: Building1[] = [
  {
    id: "AB1",
    name: "Academic Block-1",
    totalFloors: 3,
    totalRooms: 180,
    totalOccupancy: 480,
    occupied: 300,
    image: "/images/main-building.jpg",
    floors: [
      {
        id: "ground",
        name: "Ground",
        totalRoomsOnFloor: 60,
        roomOccupied: 45,
        floorArea: "700",
      },
      {
        id: "first",
        name: "First Floor",
        totalRoomsOnFloor: 60,
        roomOccupied: 40,
        floorArea: "700",
      },
      {
        id: "second",
        name: "Second Floor",
        totalRoomsOnFloor: 60,
        roomOccupied: 50,
        floorArea: "700",
      },
    ],
  },
  {
    id: "AB2",
    name: "Academic Block-2",
    totalFloors: 4,
    totalRooms: 240,
    totalOccupancy: 640,
    occupied: 360,
    image: "/images/main-building.jpg",
    floors: [
      {
        id: "ground",
        name: "Ground",
        totalRoomsOnFloor: 65,
        roomOccupied: 40,
        floorArea: "760",
      },
      {
        id: "first",
        name: "First Floor",
        totalRoomsOnFloor: 65,
        roomOccupied: 50,
        floorArea: "760",
      },
      {
        id: "second",
        name: "Second Floor",
        totalRoomsOnFloor: 55,
        roomOccupied: 55,
        floorArea: "650",
      },
      {
        id: "third",
        name: "Third Floor",
        totalRoomsOnFloor: 55,
        roomOccupied: 45,
        floorArea: "650",
      },
    ],
  },
  {
    id: "AD0",
    name: "Administration Block",
    totalFloors: 2,
    totalRooms: 80,
    totalOccupancy: 120,
    occupied: 90,
    image: "/images/main-building.jpg",
    floors: [
      {
        id: "ground",
        name: "Ground",
        totalRoomsOnFloor: 40,
        roomOccupied: 35,
        floorArea: "500",
      },
      {
        id: "first",
        name: "First Floor",
        totalRoomsOnFloor: 40,
        roomOccupied: 30,
        floorArea: "500",
      },
    ],
  },
  {
    id: "LB1",
    name: "Library Block",
    totalFloors: 3,
    totalRooms: 100,
    totalOccupancy: 300,
    occupied: 150,
    image: "/images/main-building.jpg",
    floors: [
      {
        id: "ground",
        name: "Ground",
        totalRoomsOnFloor: 35,
        roomOccupied: 20,
        floorArea: "850",
      },
      {
        id: "first",
        name: "First Floor",
        totalRoomsOnFloor: 35,
        roomOccupied: 25,
        floorArea: "850",
      },
      {
        id: "second",
        name: "Second Floor",
        totalRoomsOnFloor: 30,
        roomOccupied: 15,
        floorArea: "750",
      },
    ],
  },
  {
    id: "SPC",
    name: "Sports Complex",
    totalFloors: 1,
    totalRooms: 15,
    totalOccupancy: 200,
    occupied: 120,
    image: "/images/main-building.jpg",
    floors: [
      {
        id: "ground",
        name: "Ground",
        totalRoomsOnFloor: 15,
        roomOccupied: 10,
        floorArea: "1500",
      },
    ],
  },
];

const RoomsData: Room1[] = [
  {
    id: "AB1-G-01",
    roomName: "Classroom 101",
    capacity: 40,
    occupied: 35,
    hasSubtype: false,
    occupiedBy: null,
    roomType: "Classroom",
    floor: "ground",
    status: "Partially Allocated",
    roomArea: "60",
    buildingId: "AB1",
  },
  {
    id: "AB1-G-02",
    roomName: "Computer Lab 1",
    capacity: 25,
    occupied: 25,
    hasSubtype: true,
    occupiedBy: "Students",
    roomType: "Lab",
    floor: "ground",
    status: "Allocated",
    roomArea: "75",
    buildingId: "AB1",
  },
  {
    id: "AB1-G-03",
    roomName: "Faculty Office 1",
    capacity: 3,
    occupied: 2,
    hasSubtype: false,
    occupiedBy: "Prof. Smith, Prof. Jones",
    roomType: "Room",
    floor: "ground",
    status: "Partially Allocated",
    roomArea: "45",
    buildingId: "AB1",
  },
  {
    id: "AB1-G-04",
    roomName: "Seminar Hall",
    capacity: 100,
    occupied: 0,
    hasSubtype: true,
    occupiedBy: null,
    roomType: "Hall",
    floor: "ground",
    status: "Available",
    roomArea: "150",
    buildingId: "AB1",
  },
  {
    id: "AB1-G-05",
    roomName: "Storage Room",
    capacity: 2,
    occupied: 2,
    hasSubtype: false,
    occupiedBy: "Admin Staff",
    roomType: "Storage",
    floor: "ground",
    status: "Allocated",
    roomArea: "30",
    buildingId: "AB1",
  },
  {
    id: "AB1-G-06",
    roomName: "Washroom (Men)",
    capacity: 10,
    occupied: 0,
    hasSubtype: false,
    occupiedBy: null,
    roomType: "Washroom",
    floor: "ground",
    status: "Available",
    roomArea: "25",
    buildingId: "AB1",
  },
  {
    id: "AB1-F-01",
    roomName: "Classroom 201",
    capacity: 40,
    occupied: 40,
    hasSubtype: false,
    occupiedBy: "Students",
    roomType: "Classroom",
    floor: "first",
    status: "Allocated",
    roomArea: "60",
    buildingId: "AB1",
  },
  {
    id: "AB1-F-02",
    roomName: "Classroom 202",
    capacity: 40,
    occupied: 15,
    hasSubtype: false,
    occupiedBy: "Students",
    roomType: "Classroom",
    floor: "first",
    status: "Partially Allocated",
    roomArea: "60",
    buildingId: "AB1",
  },
  {
    id: "AB1-F-03",
    roomName: "Physics Lab",
    capacity: 30,
    occupied: 30,
    hasSubtype: false,
    occupiedBy: "Students",
    roomType: "Lab",
    floor: "first",
    status: "Allocated",
    roomArea: "80",
    buildingId: "AB1",
  },
  {
    id: "AB1-F-04",
    roomName: "Faculty Lounge",
    capacity: 10,
    occupied: 5,
    hasSubtype: false,
    occupiedBy: "Various Faculty",
    roomType: "Lounge",
    floor: "first",
    status: "Partially Allocated",
    roomArea: "50",
    buildingId: "AB1",
  },
  {
    id: "AB1-F-05",
    roomName: "Conference Room A",
    capacity: 15,
    occupied: 0,
    hasSubtype: false,
    occupiedBy: null,
    roomType: "Conference Room",
    floor: "first",
    status: "Available",
    roomArea: "70",
    buildingId: "AB1",
  },
  {
    id: "AB1-F-06",
    roomName: "Washroom (Women)",
    capacity: 10,
    occupied: 0,
    hasSubtype: false,
    occupiedBy: null,
    roomType: "Washroom",
    floor: "first",
    status: "Available",
    roomArea: "25",
    buildingId: "AB1",
  },
  {
    id: "AB1-S-01",
    roomName: "Classroom 301",
    capacity: 40,
    occupied: 0,
    hasSubtype: false,
    occupiedBy: null,
    roomType: "Classroom",
    floor: "second",
    status: "Available",
    roomArea: "60",
    buildingId: "AB1",
  },
  {
    id: "AB1-S-02",
    roomName: "Classroom 302",
    capacity: 40,
    occupied: 30,
    hasSubtype: false,
    occupiedBy: "Students",
    roomType: "Classroom",
    floor: "second",
    status: "Partially Allocated",
    roomArea: "60",
    buildingId: "AB1",
  },
  {
    id: "AB1-S-03",
    roomName: "Chemistry Lab",
    capacity: 30,
    occupied: 20,
    hasSubtype: false,
    occupiedBy: "Students",
    roomType: "Lab",
    floor: "second",
    status: "Partially Allocated",
    roomArea: "80",
    buildingId: "AB1",
  },
  {
    id: "AB1-S-04",
    roomName: "Research Office 1",
    capacity: 4,
    occupied: 4,
    hasSubtype: false,
    occupiedBy: "Researchers",
    roomType: "Room",
    floor: "second",
    status: "Allocated",
    roomArea: "50",
    buildingId: "AB1",
  },
  {
    id: "AB1-S-05",
    roomName: "Meeting Room B",
    capacity: 8,
    occupied: 2,
    hasSubtype: false,
    occupiedBy: null,
    roomType: "Meeting Room",
    floor: "second",
    status: "Partially Allocated",
    roomArea: "40",
    buildingId: "AB1",
  },
  {
    id: "AB1-S-06",
    roomName: "Washroom (Men)",
    capacity: 10,
    occupied: 0,
    hasSubtype: false,
    occupiedBy: null,
    roomType: "Washroom",
    floor: "second",
    status: "Available",
    roomArea: "25",
    buildingId: "AB1",
  },
  {
    id: "AB1-S-07",
    roomName: "Electrical Room",
    capacity: 1,
    occupied: 1,
    hasSubtype: false,
    occupiedBy: "Maintenance",
    roomType: "Room",
    floor: "second",
    status: "Allocated",
    roomArea: "20",
    buildingId: "AB1",
  },
  {
    id: "AB1-S-08",
    roomName: "Break Room",
    capacity: 12,
    occupied: 0,
    hasSubtype: false,
    occupiedBy: null,
    roomType: "Lounge",
    floor: "second",
    status: "Available",
    roomArea: "60",
    buildingId: "AB1",
  },
  {
    id: "AB2-G-01",
    roomName: "Classroom 101",
    capacity: 40,
    occupied: 35,
    hasSubtype: false,
    occupiedBy: "Students",
    roomType: "Classroom",
    floor: "ground",
    status: "Partially Allocated",
    roomArea: "60",
    buildingId: "AB2",
  },
  {
    id: "AB2-G-02",
    roomName: "Biology Lab",
    capacity: 30,
    occupied: 28,
    hasSubtype: false,
    occupiedBy: "Students",
    roomType: "Lab",
    floor: "ground",
    status: "Partially Allocated",
    roomArea: "75",
    buildingId: "AB2",
  },
  {
    id: "AB2-G-03",
    roomName: "Dean's Office",
    capacity: 1,
    occupied: 1,
    hasSubtype: false,
    occupiedBy: "Dean",
    roomType: "Room",
    floor: "ground",
    status: "Allocated",
    roomArea: "50",
    buildingId: "AB2",
  },
  {
    id: "AB2-G-04",
    roomName: "Conference Hall",
    capacity: 120,
    occupied: 0,
    hasSubtype: false,
    occupiedBy: null,
    roomType: "Hall",
    floor: "ground",
    status: "Available",
    roomArea: "200",
    buildingId: "AB2",
  },
  {
    id: "AB2-F1-01",
    roomName: "Classroom 201",
    capacity: 40,
    occupied: 40,
    hasSubtype: false,
    occupiedBy: "Students",
    roomType: "Classroom",
    floor: "first",
    status: "Allocated",
    roomArea: "60",
    buildingId: "AB2",
  },
  {
    id: "AB2-F1-02",
    roomName: "Computer Lab 2",
    capacity: 25,
    occupied: 10,
    hasSubtype: false,
    occupiedBy: "Students",
    roomType: "Lab",
    floor: "first",
    status: "Partially Allocated",
    roomArea: "75",
    buildingId: "AB2",
  },
  {
    id: "AB2-F1-03",
    roomName: "Faculty Office 2",
    capacity: 4,
    occupied: 3,
    hasSubtype: false,
    occupiedBy: "Professors",
    roomType: "Room",
    floor: "first",
    status: "Partially Allocated",
    roomArea: "55",
    buildingId: "AB2",
  },
  {
    id: "AB2-F1-04",
    roomName: "Meeting Room B",
    capacity: 8,
    occupied: 0,
    hasSubtype: true,
    occupiedBy: null,
    roomType: "Meeting Room",
    floor: "first",
    status: "Available",
    roomArea: "40",
    buildingId: "AB2",
  },
  {
    id: "AB2-F2-01",
    roomName: "Classroom 301",
    capacity: 40,
    occupied: 20,
    hasSubtype: false,
    occupiedBy: "Students",
    roomType: "Classroom",
    floor: "second",
    status: "Partially Allocated",
    roomArea: "60",
    buildingId: "AB2",
  },
  {
    id: "AB2-F2-02",
    roomName: "Classroom 302",
    capacity: 40,
    occupied: 40,
    hasSubtype: false,
    occupiedBy: "Students",
    roomType: "Classroom",
    floor: "second",
    status: "Allocated",
    roomArea: "60",
    buildingId: "AB2",
  },
  {
    id: "AB2-F2-03",
    roomName: "Physics Research Lab",
    capacity: 15,
    occupied: 15,
    hasSubtype: false,
    occupiedBy: "Researchers",
    roomType: "Lab",
    floor: "second",
    status: "Allocated",
    roomArea: "90",
    buildingId: "AB2",
  },
  {
    id: "AB2-F2-04",
    roomName: "Faculty Office 3",
    capacity: 2,
    occupied: 2,
    hasSubtype: false,
    occupiedBy: "Professors",
    roomType: "Room",
    floor: "second",
    status: "Allocated",
    roomArea: "45",
    buildingId: "AB2",
  },
  {
    id: "AB2-F3-01",
    roomName: "Classroom 401",
    capacity: 40,
    occupied: 0,
    hasSubtype: false,
    occupiedBy: null,
    roomType: "Classroom",
    floor: "third",
    status: "Available",
    roomArea: "60",
    buildingId: "AB2",
  },
  {
    id: "AB2-F3-02",
    roomName: "Electronics Lab",
    capacity: 20,
    occupied: 18,
    hasSubtype: false,
    occupiedBy: "Students",
    roomType: "Lab",
    floor: "third",
    status: "Partially Allocated",
    roomArea: "80",
    buildingId: "AB2",
  },
  {
    id: "AB2-F3-03",
    roomName: "Student Lounge",
    capacity: 50,
    occupied: 15,
    hasSubtype: false,
    occupiedBy: "Students",
    roomType: "Lounge",
    floor: "third",
    status: "Partially Allocated",
    roomArea: "100",
    buildingId: "AB2",
  },
  {
    id: "AB2-F3-04",
    roomName: "Exam Room",
    capacity: 50,
    occupied: 0,
    hasSubtype: false,
    occupiedBy: null,
    roomType: "Room",
    floor: "third",
    status: "Available",
    roomArea: "80",
    buildingId: "AB2",
  },
  {
    id: "AD0-G-01",
    roomName: "Reception",
    capacity: 5,
    occupied: 3,
    hasSubtype: false,
    occupiedBy: "Receptionists",
    roomType: "Office",
    floor: "ground",
    status: "Partially Allocated",
    roomArea: "60",
    buildingId: "AD0",
  },
  {
    id: "AD0-G-02",
    roomName: "Visitor's Lounge",
    capacity: 20,
    occupied: 5,
    hasSubtype: false,
    occupiedBy: null,
    roomType: "Lounge",
    floor: "ground",
    status: "Partially Allocated",
    roomArea: "80",
    buildingId: "AD0",
  },
  {
    id: "AD0-G-03",
    roomName: "IT Support",
    capacity: 8,
    occupied: 6,
    hasSubtype: false,
    occupiedBy: "IT Staff",
    roomType: "Office",
    floor: "ground",
    status: "Partially Allocated",
    roomArea: "50",
    buildingId: "AD0",
  },
  {
    id: "AD0-G-04",
    roomName: "Main Server Room",
    capacity: 2,
    occupied: 2,
    hasSubtype: false,
    occupiedBy: "IT Staff",
    roomType: "Utility",
    floor: "ground",
    status: "Allocated",
    roomArea: "40",
    buildingId: "AD0",
  },
  {
    id: "AD0-G-05",
    roomName: "Records Office",
    capacity: 4,
    occupied: 4,
    hasSubtype: false,
    occupiedBy: "Admin Staff",
    roomType: "Office",
    floor: "ground",
    status: "Allocated",
    roomArea: "45",
    buildingId: "AD0",
  },
  {
    id: "AD0-F1-01",
    roomName: "HR Department",
    capacity: 10,
    occupied: 8,
    hasSubtype: true,
    occupiedBy: "HR Staff",
    roomType: "Office",
    floor: "first",
    status: "Partially Allocated",
    roomArea: "70",
    buildingId: "AD0",
  },
  {
    id: "AD0-F1-02",
    roomName: "Conference Room 1",
    capacity: 12,
    occupied: 0,
    hasSubtype: false,
    occupiedBy: null,
    roomType: "Conference Room",
    floor: "first",
    status: "Available",
    roomArea: "65",
    buildingId: "AD0",
  },
  {
    id: "AD0-F1-03",
    roomName: "Director's Office",
    capacity: 1,
    occupied: 1,
    hasSubtype: false,
    occupiedBy: "Director",
    roomType: "Room",
    floor: "first",
    status: "Allocated",
    roomArea: "50",
    buildingId: "AD0",
  },
  {
    id: "AD0-F1-04",
    roomName: "Meeting Room A",
    capacity: 6,
    occupied: 0,
    hasSubtype: false,
    occupiedBy: null,
    roomType: "Meeting Room",
    floor: "first",
    status: "Available",
    roomArea: "35",
    buildingId: "AD0",
  },
  {
    id: "AD0-F1-05",
    roomName: "Washroom (Unisex)",
    capacity: 4,
    occupied: 0,
    hasSubtype: false,
    occupiedBy: null,
    roomType: "Washroom",
    floor: "first",
    status: "Available",
    roomArea: "20",
    buildingId: "AD0",
  },
  {
    id: "LB1-G-01",
    roomName: "Main Reading Hall",
    capacity: 150,
    occupied: 80,
    hasSubtype: true,
    occupiedBy: "Students",
    roomType: "Reading Room",
    floor: "ground",
    status: "Partially Allocated",
    roomArea: "250",
    buildingId: "LB1",
  },
  {
    id: "LB1-G-02",
    roomName: "Librarian's Office",
    capacity: 2,
    occupied: 1,
    hasSubtype: false,
    occupiedBy: "Librarian",
    roomType: "Room",
    floor: "ground",
    status: "Partially Allocated",
    roomArea: "40",
    buildingId: "LB1",
  },
  {
    id: "LB1-G-03",
    roomName: "Periodicals Section",
    capacity: 30,
    occupied: 10,
    hasSubtype: false,
    occupiedBy: null,
    roomType: "Reading Room",
    floor: "ground",
    status: "Partially Allocated",
    roomArea: "100",
    buildingId: "LB1",
  },
  {
    id: "LB1-G-04",
    roomName: "Multimedia Room",
    capacity: 10,
    occupied: 0,
    hasSubtype: false,
    occupiedBy: null,
    roomType: "Media Room",
    floor: "ground",
    status: "Available",
    roomArea: "60",
    buildingId: "LB1",
  },
  {
    id: "LB1-F1-01",
    roomName: "Group Study Room 1",
    capacity: 6,
    occupied: 6,
    hasSubtype: false,
    occupiedBy: "Students",
    roomType: "Study Room",
    floor: "first",
    status: "Allocated",
    roomArea: "25",
    buildingId: "LB1",
  },
  {
    id: "LB1-F1-02",
    roomName: "Group Study Room 2",
    capacity: 6,
    occupied: 0,
    hasSubtype: false,
    occupiedBy: null,
    roomType: "Study Room",
    floor: "first",
    status: "Available",
    roomArea: "25",
    buildingId: "LB1",
  },
  {
    id: "LB1-F1-03",
    roomName: "Quiet Reading Zone",
    capacity: 50,
    occupied: 35,
    hasSubtype: false,
    occupiedBy: "Students",
    roomType: "Reading Room",
    floor: "first",
    status: "Partially Allocated",
    roomArea: "150",
    buildingId: "LB1",
  },
  {
    id: "LB1-F1-04",
    roomName: "Computer Center",
    capacity: 20,
    occupied: 15,
    hasSubtype: false,
    occupiedBy: "Students",
    roomType: "Lab",
    floor: "first",
    status: "Partially Allocated",
    roomArea: "100",
    buildingId: "LB1",
  },
  {
    id: "LB1-F2-01",
    roomName: "Archival Storage",
    capacity: 1,
    occupied: 1,
    hasSubtype: false,
    occupiedBy: "Staff",
    roomType: "Storage",
    floor: "second",
    status: "Allocated",
    roomArea: "75",
    buildingId: "LB1",
  },
  {
    id: "LB1-F2-02",
    roomName: "Digital Archives Lab",
    capacity: 8,
    occupied: 5,
    hasSubtype: false,
    occupiedBy: "Staff",
    roomType: "Lab",
    floor: "second",
    status: "Partially Allocated",
    roomArea: "80",
    buildingId: "LB1",
  },
  {
    id: "SPC-G-01",
    roomName: "Main Gymnasium",
    capacity: 100,
    occupied: 60,
    hasSubtype: true,
    occupiedBy: "Students",
    roomType: "Gym",
    floor: "ground",
    status: "Partially Allocated",
    roomArea: "500",
    buildingId: "SPC",
  },
  {
    id: "SPC-G-02",
    roomName: "Indoor Basketball Court",
    capacity: 20,
    occupied: 10,
    hasSubtype: false,
    occupiedBy: "Sports Team",
    roomType: "Court",
    floor: "ground",
    status: "Partially Allocated",
    roomArea: "250",
    buildingId: "SPC",
  },
  {
    id: "SPC-G-03",
    roomName: "Changing Room (Male)",
    capacity: 30,
    occupied: 0,
    hasSubtype: false,
    occupiedBy: null,
    roomType: "Locker Room",
    floor: "ground",
    status: "Available",
    roomArea: "80",
    buildingId: "SPC",
  },
  {
    id: "SPC-G-04",
    roomName: "Changing Room (Female)",
    capacity: 30,
    occupied: 0,
    hasSubtype: false,
    occupiedBy: null,
    roomType: "Locker Room",
    floor: "ground",
    status: "Available",
    roomArea: "80",
    buildingId: "SPC",
  },
  {
    id: "SPC-G-05",
    roomName: "Coach's Office",
    capacity: 2,
    occupied: 2,
    hasSubtype: false,
    occupiedBy: "Coaches",
    roomType: "Office",
    floor: "ground",
    status: "Allocated",
    roomArea: "30",
    buildingId: "SPC",
  },
  {
    id: "SPC-G-06",
    roomName: "Equipment Storage",
    capacity: 5,
    occupied: 5,
    hasSubtype: false,
    occupiedBy: "Staff",
    roomType: "Storage",
    floor: "ground",
    status: "Allocated",
    roomArea: "40",
    buildingId: "SPC",
  },
  {
    id: "SPC-G-07",
    roomName: "First Aid Room",
    capacity: 2,
    occupied: 1,
    hasSubtype: false,
    occupiedBy: "Medic",
    roomType: "Medical",
    floor: "ground",
    status: "Partially Allocated",
    roomArea: "25",
    buildingId: "SPC",
  },
];

const SubRoomsData: Room1[] = [
  {
    id: "SPC-G-01-WS",
    roomName: "Weights Section",
    capacity: 25,
    occupied: 20,
    hasSubtype: false,
    occupiedBy: "Students",
    roomType: "Gym Area",
    floor: "ground",
    status: "Partially Allocated",
    roomArea: "150",
    buildingId: "SPC",
    parentId: "SPC-G-01",
  },
  {
    id: "SPC-G-01-CA",
    roomName: "Cardio Area",
    capacity: 30,
    occupied: 25,
    hasSubtype: false,
    occupiedBy: "Students",
    roomType: "Gym Area",
    floor: "ground",
    status: "Partially Allocated",
    roomArea: "150",
    buildingId: "SPC",
    parentId: "SPC-G-01",
  },
  {
    id: "SPC-G-01-YC",
    roomName: "Yoga/Stretching Corner",
    capacity: 15,
    occupied: 5,
    hasSubtype: false,
    occupiedBy: "Students",
    roomType: "Workout Zone",
    floor: "ground",
    status: "Partially Allocated",
    roomArea: "50",
    buildingId: "SPC",
    parentId: "SPC-G-01",
  },
  {
    id: "SPC-G-01-MS",
    roomName: "Main Sports Hall",
    capacity: 30,
    occupied: 10,
    hasSubtype: false,
    occupiedBy: "Sports Team",
    roomType: "Court",
    floor: "ground",
    status: "Partially Allocated",
    roomArea: "150",
    buildingId: "SPC",
    parentId: "SPC-G-01",
  },
  {
    id: "AB1-G-04-SA",
    roomName: "Main Seating Area",
    capacity: 100,
    occupied: 0,
    hasSubtype: false,
    occupiedBy: null,
    roomType: "Seating Area",
    floor: "ground",
    status: "Available",
    roomArea: "120",
    buildingId: "AB1",
    parentId: "AB1-G-04",
  },
  {
    id: "AB1-G-04-STG",
    roomName: "Stage",
    capacity: 5,
    occupied: 0,
    hasSubtype: false,
    occupiedBy: null,
    roomType: "Presentation Stage",
    floor: "ground",
    status: "Available",
    roomArea: "20",
    buildingId: "AB1",
    parentId: "AB1-G-04",
  },
  {
    id: "AB1-G-04-CR",
    roomName: "Control Room",
    capacity: 2,
    occupied: 0,
    hasSubtype: false,
    occupiedBy: null,
    roomType: "Utility",
    floor: "ground",
    status: "Available",
    roomArea: "10",
    buildingId: "AB1",
    parentId: "AB1-G-04",
  },
  {
    id: "LB1-G-01-SC1",
    roomName: "Study Carrel 1",
    capacity: 1,
    occupied: 1,
    hasSubtype: false,
    occupiedBy: "Student",
    roomType: "Study Carrel",
    floor: "ground",
    status: "Allocated",
    roomArea: "2",
    buildingId: "LB1",
    parentId: "LB1-G-01",
  },
  {
    id: "LB1-G-01-SC2",
    roomName: "Study Carrel 2",
    capacity: 1,
    occupied: 1,
    hasSubtype: false,
    occupiedBy: "Student",
    roomType: "Study Carrel",
    floor: "ground",
    status: "Allocated",
    roomArea: "2",
    buildingId: "LB1",
    parentId: "LB1-G-01",
  },
  {
    id: "LB1-G-01-SC3",
    roomName: "Study Carrel 3",
    capacity: 1,
    occupied: 0,
    hasSubtype: false,
    occupiedBy: null,
    roomType: "Study Carrel",
    floor: "ground",
    status: "Available",
    roomArea: "2",
    buildingId: "LB1",
    parentId: "LB1-G-01",
  },
  {
    id: "LB1-G-01-LW1",
    roomName: "Librarian Workstation 1",
    capacity: 1,
    occupied: 1,
    hasSubtype: false,
    occupiedBy: "Librarian",
    roomType: "Workstation",
    floor: "ground",
    status: "Allocated",
    roomArea: "5",
    buildingId: "LB1",
    parentId: "LB1-G-01",
  },
  {
    id: "LB1-G-01-LW2",
    roomName: "Librarian Workstation 2",
    capacity: 1,
    occupied: 1,
    hasSubtype: false,
    occupiedBy: "Librarian",
    roomType: "Workstation",
    floor: "ground",
    status: "Allocated",
    roomArea: "5",
    buildingId: "LB1",
    parentId: "LB1-G-01",
  },
  {
    id: "LB1-G-01-QA",
    roomName: "Quiet Study Area",
    capacity: 20,
    occupied: 15,
    hasSubtype: false,
    occupiedBy: null,
    roomType: "Reading Area",
    floor: "ground",
    status: "Partially Allocated",
    roomArea: "50",
    buildingId: "LB1",
    parentId: "LB1-G-01",
  },
  {
    id: "AB2-F1-04-MA",
    roomName: "Main Meeting Area",
    capacity: 8,
    occupied: 0,
    hasSubtype: false,
    occupiedBy: null,
    roomType: "Meeting Area",
    floor: "first",
    status: "Available",
    roomArea: "35",
    buildingId: "AB2",
    parentId: "AB2-F1-04",
  },
  {
    id: "AB2-F1-04-AV",
    roomName: "AV Console",
    capacity: 1,
    occupied: 0,
    hasSubtype: false,
    occupiedBy: null,
    roomType: "Utility",
    floor: "first",
    status: "Available",
    roomArea: "5",
    buildingId: "AB2",
    parentId: "AB2-F1-04",
  },
  {
    id: "AB1-G-02-WS1",
    roomName: "Workstation 1",
    capacity: 1,
    occupied: 1,
    hasSubtype: false,
    occupiedBy: "Student 1",
    roomType: "Workstation",
    floor: "ground",
    status: "Allocated",
    roomArea: "3",
    buildingId: "AB1",
    parentId: "AB1-G-02",
  },
  {
    id: "AB1-G-02-WS2",
    roomName: "Workstation 2",
    capacity: 1,
    occupied: 1,
    hasSubtype: false,
    occupiedBy: "Student 2",
    roomType: "Workstation",
    floor: "ground",
    status: "Allocated",
    roomArea: "3",
    buildingId: "AB1",
    parentId: "AB1-G-02",
  },
  {
    id: "AB1-G-02-WS3",
    roomName: "Workstation 3",
    capacity: 1,
    occupied: 1,
    hasSubtype: false,
    occupiedBy: "Student 3",
    roomType: "Workstation",
    floor: "ground",
    status: "Allocated",
    roomArea: "3",
    buildingId: "AB1",
    parentId: "AB1-G-02",
  },
  {
    id: "AB1-G-02-WS4",
    roomName: "Workstation 4",
    capacity: 1,
    occupied: 1,
    hasSubtype: false,
    occupiedBy: "Student 4",
    roomType: "Workstation",
    floor: "ground",
    status: "Allocated",
    roomArea: "3",
    buildingId: "AB1",
    parentId: "AB1-G-02",
  },
  {
    id: "AB1-G-02-WS5",
    roomName: "Workstation 5",
    capacity: 1,
    occupied: 1,
    hasSubtype: false,
    occupiedBy: "Student 5",
    roomType: "Workstation",
    floor: "ground",
    status: "Allocated",
    roomArea: "3",
    buildingId: "AB1",
    parentId: "AB1-G-02",
  },
  {
    id: "AB1-G-02-WS6",
    roomName: "Workstation 6",
    capacity: 1,
    occupied: 1,
    hasSubtype: false,
    occupiedBy: "Student 6",
    roomType: "Workstation",
    floor: "ground",
    status: "Allocated",
    roomArea: "3",
    buildingId: "AB1",
    parentId: "AB1-G-02",
  },
  {
    id: "AD0-F1-01-C1",
    roomName: "HR Manager's Cabin",
    capacity: 1,
    occupied: 1,
    hasSubtype: false,
    occupiedBy: "HR Manager",
    roomType: "Cabin",
    floor: "first",
    status: "Allocated",
    roomArea: "15",
    buildingId: "AD0",
    parentId: "AD0-F1-01",
  },
  {
    id: "AD0-F1-01-C2",
    roomName: "HR Analyst Workstation 1",
    capacity: 1,
    occupied: 1,
    hasSubtype: false,
    occupiedBy: "HR Analyst 1",
    roomType: "Workstation",
    floor: "first",
    status: "Allocated",
    roomArea: "10",
    buildingId: "AD0",
    parentId: "AD0-F1-01",
  },
  {
    id: "AD0-F1-01-C3",
    roomName: "HR Analyst Workstation 2",
    capacity: 1,
    occupied: 1,
    hasSubtype: false,
    occupiedBy: "HR Analyst 2",
    roomType: "Workstation",
    floor: "first",
    status: "Allocated",
    roomArea: "10",
    buildingId: "AD0",
    parentId: "AD0-F1-01",
  },
  {
    id: "AD0-F1-01-C4",
    roomName: "HR Workstation 3",
    capacity: 1,
    occupied: 1,
    hasSubtype: false,
    occupiedBy: "HR Intern",
    roomType: "Workstation",
    floor: "first",
    status: "Allocated",
    roomArea: "10",
    buildingId: "AD0",
    parentId: "AD0-F1-01",
  },
  {
    id: "AD0-F1-01-MTG",
    roomName: "Internal Meeting Area",
    capacity: 6,
    occupied: 2,
    hasSubtype: false,
    occupiedBy: null,
    roomType: "Meeting Area",
    floor: "first",
    status: "Partially Allocated",
    roomArea: "20",
    buildingId: "AD0",
    parentId: "AD0-F1-01",
  },
];

const RequestData: RoomRequestTable = {
  curruntPage: "1",
  totalPages: "3",
  pageSize: "10",
  requests: [
    {
      requestID: "REQ001",
      employeeName: "EMP001",
      employeeDepartment: "HR",
      requestedRoomType: "Conference Room",
      purpose: "Team Meeting - Q3 Planning",
      priority: "High",
      requestDate: "2024-07-25",
      startDate: "2024-08-10",
      purposeDesc: "This is the purpose for this meeting",
      description:
        "This request was approved because their are too many free rooms available",
      startTime: "09:00",
      endTime: "11:00",
      status: "Approved",
      allocatedRoomID: "CR005",
      approvedBy: "EMP005",
      approvalDate: "2024-07-26",
      recurrence: "None",
      endDate: "2024-07-27",
    },
    {
      requestID: "REQ002",
      employeeName: "EMP002",
      employeeDepartment: "Marketing",
      requestedRoomType: "Training Room",
      purpose: "New Product Training",
      priority: "Medium",
      requestDate: "2024-07-28",
      startDate: "2024-08-15",
      purposeDesc: "This is the purpose for this meeting",
      startTime: "13:00",
      endTime: "17:00",
      status: "Pending",
      allocatedRoomID: null,
      approvedBy: null,
      approvalDate: null,
      recurrence: "Weekly",
      endDate: "2024-07-27",
    },
    {
      requestID: "REQ003",
      employeeName: "EMP003",
      employeeDepartment: "IT",
      requestedRoomType: "Small Meeting Room",
      purpose: "Client Demo",
      priority: "High",
      requestDate: "2024-07-29",
      startDate: "2024-08-05",
      startTime: "10:30",
      endTime: "11:30",
      purposeDesc: "",
      status: "Approved",
      allocatedRoomID: "SMR002",
      approvedBy: "EMP006",
      approvalDate: "2024-07-30",
      recurrence: "None",
      endDate: "2024-07-27",
    },
    {
      requestID: "REQ004",
      employeeName: "EMP004",
      employeeDepartment: "Sales",
      requestedRoomType: "Conference Room",
      purpose: "Sales Strategy Session",
      priority: "Medium",
      requestDate: "2024-07-30",
      startDate: "2024-08-20",
      purposeDesc: "",
      startTime: "09:00",
      endTime: "12:00",
      status: "Approved",
      allocatedRoomID: "CR001",
      approvedBy: "EMP005",
      approvalDate: "2024-07-31",
      recurrence: "Monthly",
      endDate: "2024-07-27",
    },
    {
      requestID: "REQ005",
      employeeName: "EMP001",
      employeeDepartment: "HR",
      requestedRoomType: "Interview Room",
      purpose: "Candidate Interview",
      priority: "High",
      requestDate: "2024-08-01",
      startDate: "2024-08-12",
      startTime: "10:00",
      endTime: "10:45",
      purposeDesc: "",
      status: "Approved",
      allocatedRoomID: "IR003",
      approvedBy: "EMP005",
      approvalDate: "2024-08-01",
      recurrence: "None",
      endDate: "2024-07-27",
    },
    {
      requestID: "REQ006",
      employeeName: "EMP007",
      employeeDepartment: "Finance",
      requestedRoomType: "Board Room",
      purpose: "Board Meeting",
      priority: "Critical",
      requestDate: "2024-08-02",
      startDate: "2024-09-01",
      purposeDesc: "",
      startTime: "09:00",
      endTime: "16:00",
      status: "Pending",
      allocatedRoomID: null,
      approvedBy: null,
      approvalDate: null,
      recurrence: "Monthly",
      endDate: "2024-07-27",
    },
    {
      requestID: "REQ007",
      employeeName: "EMP008",
      employeeDepartment: "Operations",
      requestedRoomType: "Conference Room",
      purpose: "Project Review",
      priority: "Medium",
      requestDate: "2024-08-03",
      startDate: "2024-08-18",
      purposeDesc: "This is the main purpose of meeting",
      description:
        "Meeting reject because thier is no project reviewer available",
      startTime: "14:00",
      endTime: "15:30",
      status: "Rejected",
      allocatedRoomID: null,
      approvedBy: "EMP005",
      approvalDate: "2024-08-04",
      recurrence: "None",
      endDate: "2024-07-27",
    },
    {
      requestID: "REQ008",
      employeeName: "EMP009",
      employeeDepartment: "R&D",
      requestedRoomType: "Lab",
      purpose: "Experiment Setup",
      priority: "Low",
      requestDate: "2024-08-04",
      startDate: "2024-08-25",
      startTime: "08:00",
      purposeDesc: "",
      endTime: "12:00",
      status: "Approved",
      allocatedRoomID: "LAB001",
      approvedBy: "EMP006",
      approvalDate: "2024-08-05",
      recurrence: "None",
      endDate: "2024-07-27",
    },
    {
      requestID: "REQ009",
      employeeName: "EMP010",
      employeeDepartment: "Customer Support",
      requestedRoomType: "Training Room",
      purpose: "Customer Service Workshop",
      priority: "High",
      requestDate: "2024-08-05",
      startDate: "2024-09-01",
      startTime: "09:00",
      endTime: "17:00",
      purposeDesc: "",
      status: "Pending",
      allocatedRoomID: null,
      approvedBy: null,
      approvalDate: null,
      recurrence: "Quarterly",
      endDate: "2024-07-27",
    },
    {
      requestID: "REQ010",
      purposeDesc: "",
      employeeName: "EMP002",
      employeeDepartment: "Marketing",
      requestedRoomType: "Small Meeting Room",
      purpose: "Brainstorming Session",
      priority: "Medium",
      requestDate: "2024-08-06",
      startDate: "2024-08-08",
      startTime: "14:00",
      endTime: "15:00",
      status: "Approved",
      allocatedRoomID: "SMR001",
      approvedBy: "EMP005",
      approvalDate: "2024-08-06",
      recurrence: "None",
      endDate: "2024-07-27",
    },
    {
      requestID: "REQ011",
      employeeName: "EMP011",
      employeeDepartment: "HR",
      requestedRoomType: "Interview Room",
      purpose: "Final Round Interview",
      priority: "High",
      requestDate: "2024-08-07",
      startDate: "2024-08-14",
      startTime: "11:00",
      endTime: "12:00",
      purposeDesc: "",
      status: "Approved",
      allocatedRoomID: "IR002",
      approvedBy: "EMP005",
      approvalDate: "2024-08-07",
      recurrence: "None",
      endDate: "2024-07-27",
    },
    {
      requestID: "REQ012",
      employeeName: "EMP012",
      employeeDepartment: "Engineering",
      requestedRoomType: "Conference Room",
      purpose: "Sprint Planning",
      priority: "High",
      requestDate: "2024-08-08",
      startDate: "2024-08-16",
      startTime: "10:00",
      endTime: "12:00",
      purposeDesc: "",
      status: "Pending",
      allocatedRoomID: null,
      approvedBy: null,
      approvalDate: null,
      recurrence: "Bi-Weekly",
      endDate: "2024-07-27",
    },
    {
      requestID: "REQ013",
      employeeName: "EMP013",
      employeeDepartment: "Product",
      requestedRoomType: "Small Meeting Room",
      purpose: "UI/UX Review",
      priority: "Medium",
      requestDate: "2024-08-08",
      startDate: "2024-08-11",
      startTime: "14:30",
      endTime: "15:00",
      status: "Approved",
      purposeDesc: "",
      allocatedRoomID: "SMR003",
      approvedBy: "EMP006",
      approvalDate: "2024-08-09",
      recurrence: "None",
      endDate: "2024-07-27",
    },
    {
      requestID: "REQ014",
      employeeName: "EMP001",
      employeeDepartment: "HR",
      requestedRoomType: "Training Room",
      purpose: "Onboarding Session",
      priority: "High",
      requestDate: "2024-08-09",
      startDate: "2024-09-05",
      purposeDesc: "",
      startTime: "09:00",
      endTime: "16:00",
      status: "Pending",
      allocatedRoomID: null,
      approvedBy: null,
      approvalDate: null,
      recurrence: "Monthly",
      endDate: "2024-07-27",
    },
    {
      requestID: "REQ015",
      employeeName: "EMP014",
      employeeDepartment: "Finance",
      requestedRoomType: "Board Room",
      purpose: "Budget Review",
      priority: "Critical",
      requestDate: "2024-08-10",
      startDate: "2024-08-22",
      startTime: "10:00",
      endTime: "12:00",
      purposeDesc: "",
      status: "Approved",
      allocatedRoomID: "BR001",
      approvedBy: "EMP005",
      approvalDate: "2024-08-11",
      recurrence: "None",
      endDate: "2024-07-27",
    },
    {
      requestID: "REQ016",
      employeeName: "EMP015",
      employeeDepartment: "Marketing",
      requestedRoomType: "Small Meeting Room",
      purpose: "Content Strategy",
      priority: "Medium",
      requestDate: "2024-08-11",
      startDate: "2024-08-13",
      startTime: "15:00",
      endTime: "16:00",
      purposeDesc: "",
      status: "Approved",
      allocatedRoomID: "SMR001",
      approvedBy: "EMP005",
      approvalDate: "2024-08-11",
      recurrence: "None",
      endDate: "2024-07-27",
    },
    {
      requestID: "REQ017",
      employeeName: "EMP008",
      employeeDepartment: "Operations",
      requestedRoomType: "Conference Room",
      purpose: "Vendor Negotiation",
      priority: "High",
      requestDate: "2024-08-12",
      startDate: "2024-08-28",
      startTime: "11:00",
      endTime: "13:00",
      status: "Rejected",
      allocatedRoomID: null,
      purposeDesc: "",
      approvedBy: "EMP005",
      approvalDate: "2024-08-13",
      recurrence: "None",
      endDate: "2024-07-27",
    },
    {
      requestID: "REQ018",
      employeeName: "EMP016",
      employeeDepartment: "R&D",
      requestedRoomType: "Lab",
      purpose: "New Material Testing",
      priority: "High",
      requestDate: "2024-08-13",
      startDate: "2024-08-20",
      startTime: "13:00",
      purposeDesc: "",
      endTime: "16:00",
      status: "Approved",
      allocatedRoomID: "LAB002",
      approvedBy: "EMP006",
      approvalDate: "2024-08-14",
      recurrence: "Weekly",
      endDate: "2024-07-27",
    },
    {
      requestID: "REQ019",
      employeeName: "EMP017",
      employeeDepartment: "Customer Support",
      requestedRoomType: "Small Meeting Room",
      purpose: "Team Huddle",
      priority: "Low",
      requestDate: "2024-08-14",
      startDate: "2024-08-15",
      startTime: "09:30",
      purposeDesc: "",
      endTime: "10:00",
      status: "Approved",
      allocatedRoomID: "SMR004",
      approvedBy: "EMP006",
      approvalDate: "2024-08-14",
      recurrence: "None",
      endDate: "2024-07-27",
    },
    {
      requestID: "REQ020",
      employeeName: "EMP018",
      employeeDepartment: "Product",
      requestedRoomType: "Conference Room",
      purpose: "Roadmap Presentation",
      priority: "High",
      requestDate: "2024-08-15",
      startDate: "2024-08-29",
      purposeDesc: "",
      startTime: "10:00",
      endTime: "11:00",
      status: "Pending",
      allocatedRoomID: null,
      approvedBy: null,
      approvalDate: null,
      recurrence: "None",
      endDate: "2024-07-27",
    },
    {
      requestID: "REQ021",
      employeeName: "EMP019",
      employeeDepartment: "IT",
      requestedRoomType: "Training Room",
      purpose: "Software Installation Workshop",
      priority: "Medium",
      requestDate: "2024-08-16",
      startDate: "2024-09-10",
      purposeDesc: "",
      startTime: "09:00",
      endTime: "12:00",
      status: "Approved",
      allocatedRoomID: "TR001",
      approvedBy: "EMP005",
      approvalDate: "2024-08-17",
      recurrence: "None",
      endDate: "2024-07-27",
    },
    {
      requestID: "REQ022",
      employeeName: "EMP020",
      employeeDepartment: "Sales",
      requestedRoomType: "Conference Room",
      purpose: "Quarterly Review",
      priority: "Critical",
      requestDate: "2024-08-17",
      startDate: "2024-09-05",
      startTime: "13:00",
      endTime: "16:00",
      purposeDesc: "",
      status: "Pending",
      allocatedRoomID: null,
      approvedBy: null,
      approvalDate: null,
      recurrence: "Quarterly",
      endDate: "2024-07-27",
    },
    {
      requestID: "REQ023",
      employeeName: "EMP021",
      employeeDepartment: "Engineering",
      requestedRoomType: "Small Meeting Room",
      purpose: "Code Review",
      priority: "Medium",
      requestDate: "2024-08-18",
      startDate: "2024-08-21",
      startTime: "10:00",
      endTime: "11:00",
      purposeDesc: "",
      status: "Approved",
      allocatedRoomID: "SMR005",
      approvedBy: "EMP006",
      approvalDate: "2024-08-19",
      recurrence: "None",
      endDate: "2024-07-27",
    },
    {
      requestID: "REQ024",
      employeeName: "EMP022",
      employeeDepartment: "Operations",
      requestedRoomType: "Board Room",
      purpose: "Leadership Summit",
      priority: "Critical",
      requestDate: "2024-08-19",
      startDate: "2024-09-15",
      startTime: "09:00",
      endTime: "17:00",
      purposeDesc: "",
      status: "Pending",
      allocatedRoomID: null,
      approvedBy: null,
      approvalDate: null,
      recurrence: "Annually",
      endDate: "2024-07-27",
    },
    {
      requestID: "REQ025",
      employeeName: "EMP023",
      employeeDepartment: "HR",
      requestedRoomType: "Interview Room",
      purpose: "Recruitment Drive",
      priority: "High",
      requestDate: "2024-08-20",
      startDate: "2024-09-02",
      startTime: "09:00",
      endTime: "16:00",
      status: "Approved",
      allocatedRoomID: "IR001",
      approvedBy: "EMP005",
      approvalDate: "2024-08-21",
      recurrence: "None",
      endDate: "2024-07-27",
    },
    {
      requestID: "REQ026",
      employeeName: "EMP024",
      employeeDepartment: "Finance",
      requestedRoomType: "Conference Room",
      purpose: "Investor Presentation",
      priority: "Critical",
      requestDate: "2024-08-21",
      startDate: "2024-09-12",
      startTime: "10:00",
      endTime: "11:00",
      status: "Approved",
      allocatedRoomID: "CR003",
      approvedBy: "EMP005",
      approvalDate: "2024-08-22",
      recurrence: "None",
      endDate: "2024-07-27",
    },
    {
      requestID: "REQ027",
      employeeName: "EMP025",
      employeeDepartment: "Marketing",
      requestedRoomType: "Training Room",
      purpose: "Social Media Strategy Workshop",
      priority: "Medium",
      requestDate: "2024-08-22",
      startDate: "2024-09-08",
      startTime: "14:00",
      endTime: "17:00",
      status: "Pending",
      allocatedRoomID: null,
      approvedBy: null,
      approvalDate: null,
      recurrence: "None",
      endDate: "2024-07-27",
    },
    {
      requestID: "REQ028",
      employeeName: "EMP026",
      employeeDepartment: "R&D",
      requestedRoomType: "Lab",
      purpose: "Prototype Assembly",
      priority: "High",
      requestDate: "2024-08-23",
      startDate: "2024-09-01",
      startTime: "09:00",
      endTime: "12:00",
      status: "Approved",
      allocatedRoomID: "LAB003",
      approvedBy: "EMP006",
      approvalDate: "2024-08-24",
      recurrence: "Bi-Weekly",
      endDate: "2024-07-27",
    },
    {
      requestID: "REQ029",
      employeeName: "EMP027",
      employeeDepartment: "Customer Support",
      requestedRoomType: "Small Meeting Room",
      purpose: "Quarterly Performance Review",
      priority: "Low",
      requestDate: "2024-08-24",
      startDate: "2024-08-27",
      startTime: "10:00",
      endTime: "11:00",
      status: "Approved",
      allocatedRoomID: "SMR006",
      approvedBy: "EMP006",
      approvalDate: "2024-08-25",
      recurrence: "Quarterly",
      endDate: "2024-07-27",
    },
    {
      requestID: "REQ030",
      employeeName: "EMP028",
      employeeDepartment: "Sales",
      requestedRoomType: "Conference Room",
      purpose: "Client Follow-up Meeting",
      priority: "Medium",
      requestDate: "2024-08-25",
      startDate: "2024-08-30",
      startTime: "14:00",
      endTime: "15:00",
      status: "Pending",
      allocatedRoomID: null,
      approvedBy: null,
      approvalDate: null,
      recurrence: "None",
      endDate: "2024-07-27",
    },
  ],
};

const DashboardData7D = {
  totalBuildings: "4",
  totalFloors: "18",
  totalRooms: "1560",
  totalFacilities: "45",
  avgOccupancy: "62",
  activeSessions: "55",
  maintenanceIssues: "5",
  utilizationRequests: "120",
  availabeFacilities: "12",
  graphData: [
    { time: "Day 1 - Morning", "Occupancy Rate": 60 },
    { time: "Day 1 - Afternoon", "Occupancy Rate": 85 },
    { time: "Day 2 - Morning", "Occupancy Rate": 65 },
    { time: "Day 2 - Afternoon", "Occupancy Rate": 90 },
    { time: "Day 3 - Morning", "Occupancy Rate": 70 },
    { time: "Day 3 - Afternoon", "Occupancy Rate": 95 },
    { time: "Day 4 - Morning", "Occupancy Rate": 55 },
    { time: "Day 4 - Afternoon", "Occupancy Rate": 88 },
    { time: "Day 5 - Morning", "Occupancy Rate": 40 },
    { time: "Day 5 - Afternoon", "Occupancy Rate": 75 },
    { time: "Day 6 - Morning", "Occupancy Rate": 20 },
    { time: "Day 6 - Afternoon", "Occupancy Rate": 35 },
    { time: "Day 7 - Morning", "Occupancy Rate": 25 },
    { time: "Day 7 - Afternoon", "Occupancy Rate": 40 },
  ],
};
const DashboardData30D = {
  totalBuildings: "4",
  totalFloors: "18",
  totalRooms: "1560",
  totalFacilities: "45",
  avgOccupancy: "68",
  activeSessions: "65",
  maintenanceIssues: "8",
  utilizationRequests: "150",
  availabeFacilities: "10",
  graphData: [
    { time: "Day 1", "Occupancy Rate": 60 },
    { time: "Day 3", "Occupancy Rate": 75 },
    { time: "Day 5", "Occupancy Rate": 80 },
    { time: "Day 7", "Occupancy Rate": 70 },
    { time: "Day 9", "Occupancy Rate": 65 },
    { time: "Day 11", "Occupancy Rate": 85 },
    { time: "Day 13", "Occupancy Rate": 90 },
    { time: "Day 15", "Occupancy Rate": 82 },
    { time: "Day 17", "Occupancy Rate": 78 },
    { time: "Day 19", "Occupancy Rate": 88 },
    { time: "Day 21", "Occupancy Rate": 95 },
    { time: "Day 23", "Occupancy Rate": 70 },
    { time: "Day 25", "Occupancy Rate": 68 },
    { time: "Day 27", "Occupancy Rate": 75 },
    { time: "Day 29", "Occupancy Rate": 80 },
  ],
};

const RoomInformation: RoomInfo[] = [
  {
    id: "AB1-G-01",
    roomName: "Classroom 101",
    capacity: 40,
    occupied: 35,
    hasSubtype: false,
    occupiedBy: null,
    roomType: "Classroom",
    building: "Academic Block 1",
    floor: "ground",
    status: "Partially Allocated",
    roomArea: "60",
    occupants: [
      {
        occupantName: "Introduction to Physics",
        type: "Lecture",
        startTime: "2025-08-13T09:00:00.000Z",
        endTime: "2025-08-13T10:30:00.000Z",
      },
    ],
  },
  {
    id: "AB1-G-02",
    roomName: "Academic Block 1 - Computer Lab 1",
    capacity: 25,
    occupied: 25,
    hasSubtype: true,
    occupiedBy: null,
    roomType: "Lab",
    building: "Academic Block 1",
    floor: "ground",
    status: "Allocated",
    roomArea: "75",
    occupants: [
      {
        occupantName: "Software Development Lab",
        type: "Lab Session",
        startTime: "2025-08-13T09:00:00.000Z",
        endTime: "2025-08-13T11:00:00.000Z",
      },
    ],
  },
  {
    id: "AB1-G-03",
    roomName: "Faculty Office 1",
    capacity: 3,
    occupied: 2,
    hasSubtype: false,
    occupiedBy: "Prof. Smith, Prof. Jones",
    roomType: "Room",
    building: "Academic Block 1",
    floor: "ground",
    status: "Partially Allocated",
    roomArea: "45",
    occupants: [],
  },
  {
    id: "AB1-G-04",
    roomName: "Seminar Hall",
    capacity: 100,
    occupied: 0,
    hasSubtype: true,
    occupiedBy: null,
    roomType: "Hall",
    building: "Academic Block 1",
    floor: "ground",
    status: "Available",
    roomArea: "150",
    occupants: [],
  },
  {
    id: "AB1-G-05",
    roomName: "Storage Room",
    capacity: 2,
    occupied: 2,
    hasSubtype: false,
    occupiedBy: "Admin Staff",
    roomType: "Storage",
    building: "Academic Block 1",
    floor: "ground",
    status: "Allocated",
    roomArea: "30",
    occupants: [],
  },
  {
    id: "AB1-G-06",
    roomName: "Washroom (Men)",
    capacity: 10,
    occupied: 0,
    hasSubtype: false,
    occupiedBy: null,
    roomType: "Washroom",
    building: "Academic Block 1",
    floor: "ground",
    status: "Available",
    roomArea: "25",
    occupants: [],
  },
  {
    id: "AB1-F-01",
    roomName: "Academic Block 1 - Classroom 201",
    capacity: 40,
    occupied: 40,
    hasSubtype: false,
    occupiedBy: null,
    roomType: "Classroom",
    building: "Academic Block 1",
    floor: "first",
    status: "Allocated",
    roomArea: "60",
    occupants: [
      {
        occupantName: "Introduction to Computer Science",
        type: "Lecture",
        startTime: "2025-08-13T10:00:00.000Z",
        endTime: "2025-08-13T11:30:00.000Z",
      },
      {
        occupantName: "Data Structures Lab",
        type: "Lab Session",
        startTime: "2025-08-13T14:00:00.000Z",
        endTime: "2025-08-13T16:00:00.000Z",
      },
    ],
  },
  {
    id: "AB1-F-02",
    roomName: "Classroom 202",
    capacity: 40,
    occupied: 15,
    hasSubtype: false,
    occupiedBy: "Students",
    roomType: "Classroom",
    building: "Academic Block 1",
    floor: "first",
    status: "Partially Allocated",
    roomArea: "60",
    occupants: [],
  },
  {
    id: "AB1-F-03",
    roomName: "Physics Lab",
    capacity: 30,
    occupied: 30,
    hasSubtype: false,
    occupiedBy: "Students",
    roomType: "Lab",
    building: "Academic Block 1",
    floor: "first",
    status: "Allocated",
    roomArea: "80",
    occupants: [
      {
        occupantName: "Advanced Physics Lab",
        type: "Lab Session",
        startTime: "2025-08-13T10:00:00.000Z",
        endTime: "2025-08-13T12:00:00.000Z",
      },
    ],
  },
  {
    id: "AB1-F-04",
    roomName: "Faculty Lounge",
    capacity: 10,
    occupied: 5,
    hasSubtype: false,
    occupiedBy: "Various Faculty",
    roomType: "Lounge",
    building: "Academic Block 1",
    floor: "first",
    status: "Partially Allocated",
    roomArea: "50",
    occupants: [],
  },
  {
    id: "AB1-F-05",
    roomName: "Conference Room A",
    capacity: 15,
    occupied: 0,
    hasSubtype: false,
    occupiedBy: null,
    roomType: "Conference Room",
    building: "Academic Block 1",
    floor: "first",
    status: "Available",
    roomArea: "70",
    occupants: [],
  },
  {
    id: "AB1-F-06",
    roomName: "Washroom (Women)",
    capacity: 10,
    occupied: 0,
    hasSubtype: false,
    occupiedBy: null,
    roomType: "Washroom",
    building: "Academic Block 1",
    floor: "first",
    status: "Available",
    roomArea: "25",
    occupants: [],
  },
  {
    id: "AB1-S-01",
    roomName: "Classroom 301",
    capacity: 40,
    occupied: 0,
    hasSubtype: false,
    occupiedBy: null,
    roomType: "Classroom",
    building: "Academic Block 1",
    floor: "second",
    status: "Available",
    roomArea: "60",
    occupants: [],
  },
  {
    id: "AB1-S-02",
    roomName: "Classroom 302",
    capacity: 40,
    occupied: 30,
    hasSubtype: false,
    occupiedBy: "Students",
    roomType: "Classroom",
    building: "Academic Block 1",
    floor: "second",
    status: "Partially Allocated",
    roomArea: "60",
    occupants: [],
  },
  {
    id: "AB1-S-03",
    roomName: "Chemistry Lab",
    capacity: 30,
    occupied: 20,
    hasSubtype: false,
    occupiedBy: "Students",
    roomType: "Lab",
    building: "Academic Block 1",
    floor: "second",
    status: "Partially Allocated",
    roomArea: "80",
    occupants: [],
  },
  {
    id: "AB1-S-04",
    roomName: "Academic Block 1 - Research Office 1",
    capacity: 4,
    occupied: 4,
    hasSubtype: false,
    occupiedBy: null,
    roomType: "Room",
    building: "Academic Block 1",
    floor: "second",
    status: "Allocated",
    roomArea: "50",
    occupants: [
      {
        occupantName: "Dr. Miller",
        type: "Researcher",
        startTime: "2025-08-13T08:00:00.000Z",
        endTime: "2025-08-13T17:00:00.000Z",
      },
      {
        occupantName: "Dr. Chen",
        type: "Researcher",
        startTime: "2025-08-13T09:30:00.000Z",
        endTime: "2025-08-13T18:30:00.000Z",
      },
    ],
  },
  {
    id: "AB1-S-05",
    roomName: "Meeting Room B",
    capacity: 8,
    occupied: 2,
    hasSubtype: false,
    occupiedBy: null,
    roomType: "Meeting Room",
    building: "Academic Block 1",
    floor: "second",
    status: "Partially Allocated",
    roomArea: "40",
    occupants: [],
  },
  {
    id: "AB1-S-06",
    roomName: "Washroom (Men)",
    capacity: 10,
    occupied: 0,
    hasSubtype: false,
    occupiedBy: null,
    roomType: "Washroom",
    building: "Academic Block 1",
    floor: "second",
    status: "Available",
    roomArea: "25",
    occupants: [],
  },
  {
    id: "AB1-S-07",
    roomName: "Electrical Room",
    capacity: 1,
    occupied: 1,
    hasSubtype: false,
    occupiedBy: "Maintenance",
    roomType: "Room",
    building: "Academic Block 1",
    floor: "second",
    status: "Allocated",
    roomArea: "20",
    occupants: [],
  },
  {
    id: "AB1-S-08",
    roomName: "Break Room",
    capacity: 12,
    occupied: 0,
    hasSubtype: false,
    occupiedBy: null,
    roomType: "Lounge",
    building: "Academic Block 1",
    floor: "second",
    status: "Available",
    roomArea: "60",
    occupants: [],
  },
  {
    id: "AB2-G-01",
    roomName: "Classroom 101",
    capacity: 40,
    occupied: 35,
    hasSubtype: false,
    occupiedBy: "Students",
    roomType: "Classroom",
    building: "Academic Block 2",
    floor: "ground",
    status: "Partially Allocated",
    roomArea: "60",
    occupants: [],
  },
  {
    id: "AB2-G-02",
    roomName: "Biology Lab",
    capacity: 30,
    occupied: 28,
    hasSubtype: false,
    occupiedBy: "Students",
    roomType: "Lab",
    building: "Academic Block 2",
    floor: "ground",
    status: "Partially Allocated",
    roomArea: "75",
    occupants: [],
  },
  {
    id: "AB2-G-03",
    roomName: "Dean's Office",
    capacity: 1,
    occupied: 1,
    hasSubtype: false,
    occupiedBy: "Dean",
    roomType: "Room",
    building: "Academic Block 2",
    floor: "ground",
    status: "Allocated",
    roomArea: "50",
    occupants: [],
  },
  {
    id: "AB2-G-04",
    roomName: "Conference Hall",
    capacity: 120,
    occupied: 0,
    hasSubtype: false,
    occupiedBy: null,
    roomType: "Hall",
    building: "Academic Block 2",
    floor: "ground",
    status: "Available",
    roomArea: "200",
    occupants: [],
  },
  {
    id: "AB2-F1-01",
    roomName: "Classroom 201",
    capacity: 40,
    occupied: 40,
    hasSubtype: false,
    occupiedBy: "Students",
    roomType: "Classroom",
    building: "Academic Block 2",
    floor: "first",
    status: "Allocated",
    roomArea: "60",
    occupants: [],
  },
  {
    id: "AB2-F1-02",
    roomName: "Computer Lab 2",
    capacity: 25,
    occupied: 10,
    hasSubtype: false,
    occupiedBy: "Students",
    roomType: "Lab",
    building: "Academic Block 2",
    floor: "first",
    status: "Partially Allocated",
    roomArea: "75",
    occupants: [],
  },
  {
    id: "AB2-F1-03",
    roomName: "Faculty Office 2",
    capacity: 4,
    occupied: 3,
    hasSubtype: false,
    occupiedBy: "Professors",
    roomType: "Room",
    building: "Academic Block 2",
    floor: "first",
    status: "Partially Allocated",
    roomArea: "55",
    occupants: [],
  },
  {
    id: "AB2-F1-04",
    roomName: "Meeting Room B",
    capacity: 8,
    occupied: 0,
    hasSubtype: true,
    occupiedBy: null,
    roomType: "Meeting Room",
    building: "Academic Block 2",
    floor: "first",
    status: "Available",
    roomArea: "40",
    occupants: [],
  },
  {
    id: "AB2-F2-01",
    roomName: "Classroom 301",
    capacity: 40,
    occupied: 20,
    hasSubtype: false,
    occupiedBy: "Students",
    roomType: "Classroom",
    building: "Academic Block 2",
    floor: "second",
    status: "Partially Allocated",
    roomArea: "60",
    occupants: [],
  },
  {
    id: "AB2-F2-02",
    roomName: "Classroom 302",
    capacity: 40,
    occupied: 40,
    hasSubtype: false,
    occupiedBy: "Students",
    roomType: "Classroom",
    building: "Academic Block 2",
    floor: "second",
    status: "Allocated",
    roomArea: "60",
    occupants: [],
  },
  {
    id: "AB2-F2-03",
    roomName: "Physics Research Lab",
    capacity: 15,
    occupied: 15,
    hasSubtype: false,
    occupiedBy: "Researchers",
    roomType: "Lab",
    building: "Academic Block 2",
    floor: "second",
    status: "Allocated",
    roomArea: "90",
    occupants: [],
  },
  {
    id: "AB2-F2-04",
    roomName: "Faculty Office 3",
    capacity: 2,
    occupied: 2,
    hasSubtype: false,
    occupiedBy: "Professors",
    roomType: "Room",
    building: "Academic Block 2",
    floor: "second",
    status: "Allocated",
    roomArea: "45",
    occupants: [],
  },
  {
    id: "AB2-F3-01",
    roomName: "Classroom 401",
    capacity: 40,
    occupied: 0,
    hasSubtype: false,
    occupiedBy: null,
    roomType: "Classroom",
    building: "Academic Block 2",
    floor: "third",
    status: "Available",
    roomArea: "60",
    occupants: [],
  },
  {
    id: "AB2-F3-02",
    roomName: "Electronics Lab",
    capacity: 20,
    occupied: 18,
    hasSubtype: false,
    occupiedBy: "Students",
    roomType: "Lab",
    building: "Academic Block 2",
    floor: "third",
    status: "Partially Allocated",
    roomArea: "80",
    occupants: [],
  },
  {
    id: "AB2-F3-03",
    roomName: "Student Lounge",
    capacity: 50,
    occupied: 15,
    hasSubtype: false,
    occupiedBy: "Students",
    roomType: "Lounge",
    building: "Academic Block 2",
    floor: "third",
    status: "Partially Allocated",
    roomArea: "100",
    occupants: [],
  },
  {
    id: "AB2-F3-04",
    roomName: "Exam Room",
    capacity: 50,
    occupied: 0,
    hasSubtype: false,
    occupiedBy: null,
    roomType: "Room",
    building: "Academic Block 2",
    floor: "third",
    status: "Available",
    roomArea: "80",
    occupants: [],
  },
  {
    id: "AD0-G-01",
    roomName: "Reception",
    capacity: 5,
    occupied: 3,
    hasSubtype: false,
    occupiedBy: "Receptionists",
    roomType: "Office",
    building: "Admin Block",
    floor: "ground",
    status: "Partially Allocated",
    roomArea: "60",
    occupants: [],
  },
  {
    id: "AD0-G-02",
    roomName: "Visitor's Lounge",
    capacity: 20,
    occupied: 5,
    hasSubtype: false,
    occupiedBy: null,
    roomType: "Lounge",
    building: "Admin Block",
    floor: "ground",
    status: "Partially Allocated",
    roomArea: "80",
    occupants: [],
  },
  {
    id: "AD0-G-03",
    roomName: "IT Support",
    capacity: 8,
    occupied: 6,
    hasSubtype: false,
    occupiedBy: "IT Staff",
    roomType: "Office",
    building: "Admin Block",
    floor: "ground",
    status: "Partially Allocated",
    roomArea: "50",
    occupants: [],
  },
  {
    id: "AD0-G-04",
    roomName: "Main Server Room",
    capacity: 2,
    occupied: 2,
    hasSubtype: false,
    occupiedBy: "IT Staff",
    roomType: "Utility",
    building: "Admin Block",
    floor: "ground",
    status: "Allocated",
    roomArea: "40",
    occupants: [],
  },
  {
    id: "AD0-G-05",
    roomName: "Records Office",
    capacity: 4,
    occupied: 4,
    hasSubtype: false,
    occupiedBy: "Admin Staff",
    roomType: "Office",
    building: "Admin Block",
    floor: "ground",
    status: "Allocated",
    roomArea: "45",
    occupants: [],
  },
  {
    id: "AD0-F1-01",
    roomName: "HR Department",
    capacity: 10,
    occupied: 8,
    hasSubtype: true,
    occupiedBy: null,
    roomType: "Office",
    building: "Admin Block",
    floor: "first",
    status: "Partially Allocated",
    roomArea: "70",
    occupants: [],
  },
  {
    id: "AD0-F1-02",
    roomName: "Conference Room 1",
    capacity: 12,
    occupied: 0,
    hasSubtype: false,
    occupiedBy: null,
    roomType: "Conference Room",
    building: "Admin Block",
    floor: "first",
    status: "Available",
    roomArea: "65",
    occupants: [],
  },
  {
    id: "AD0-F1-03",
    roomName: "Director's Office",
    capacity: 1,
    occupied: 1,
    hasSubtype: false,
    occupiedBy: "Director",
    roomType: "Room",
    building: "Admin Block",
    floor: "first",
    status: "Allocated",
    roomArea: "50",
    occupants: [],
  },
  {
    id: "AD0-F1-04",
    roomName: "Meeting Room A",
    capacity: 6,
    occupied: 0,
    hasSubtype: false,
    occupiedBy: null,
    roomType: "Meeting Room",
    building: "Admin Block",
    floor: "first",
    status: "Available",
    roomArea: "35",
    occupants: [],
  },
  {
    id: "AD0-F1-05",
    roomName: "Washroom (Unisex)",
    capacity: 4,
    occupied: 0,
    hasSubtype: false,
    occupiedBy: null,
    roomType: "Washroom",
    building: "Admin Block",
    floor: "first",
    status: "Available",
    roomArea: "20",
    occupants: [],
  },
  {
    id: "LB1-G-01",
    roomName: "Main Reading Hall",
    capacity: 150,
    occupied: 80,
    hasSubtype: true,
    occupiedBy: null,
    roomType: "Reading Room",
    building: "Library Block",
    floor: "ground",
    status: "Partially Allocated",
    roomArea: "250",
    occupants: [],
  },
  {
    id: "LB1-G-02",
    roomName: "Librarian's Office",
    capacity: 2,
    occupied: 1,
    hasSubtype: false,
    occupiedBy: "Librarian",
    roomType: "Room",
    building: "Library Block",
    floor: "ground",
    status: "Partially Allocated",
    roomArea: "40",
    occupants: [],
  },
  {
    id: "LB1-G-03",
    roomName: "Periodicals Section",
    capacity: 30,
    occupied: 10,
    hasSubtype: false,
    occupiedBy: null,
    roomType: "Reading Room",
    building: "Library Block",
    floor: "ground",
    status: "Partially Allocated",
    roomArea: "100",
    occupants: [],
  },
  {
    id: "LB1-G-04",
    roomName: "Multimedia Room",
    capacity: 10,
    occupied: 0,
    hasSubtype: false,
    occupiedBy: null,
    roomType: "Media Room",
    building: "Library Block",
    floor: "ground",
    status: "Available",
    roomArea: "60",
    occupants: [],
  },
  {
    id: "LB1-F1-01",
    roomName: "Group Study Room 1",
    capacity: 6,
    occupied: 6,
    hasSubtype: false,
    occupiedBy: "Students",
    roomType: "Study Room",
    building: "Library Block",
    floor: "first",
    status: "Allocated",
    roomArea: "25",
    occupants: [],
  },
  {
    id: "LB1-F1-02",
    roomName: "Group Study Room 2",
    capacity: 6,
    occupied: 0,
    hasSubtype: false,
    occupiedBy: null,
    roomType: "Study Room",
    building: "Library Block",
    floor: "first",
    status: "Available",
    roomArea: "25",
    occupants: [],
  },
  {
    id: "LB1-F1-03",
    roomName: "Quiet Reading Zone",
    capacity: 50,
    occupied: 35,
    hasSubtype: false,
    occupiedBy: "Students",
    roomType: "Reading Room",
    building: "Library Block",
    floor: "first",
    status: "Partially Allocated",
    roomArea: "150",
    occupants: [],
  },
  {
    id: "LB1-F1-04",
    roomName: "Computer Center",
    capacity: 20,
    occupied: 15,
    hasSubtype: false,
    occupiedBy: "Students",
    roomType: "Lab",
    building: "Library Block",
    floor: "first",
    status: "Partially Allocated",
    roomArea: "100",
    occupants: [],
  },
  {
    id: "LB1-F2-01",
    roomName: "Archival Storage",
    capacity: 1,
    occupied: 1,
    hasSubtype: false,
    occupiedBy: "Staff",
    roomType: "Storage",
    building: "Library Block",
    floor: "second",
    status: "Allocated",
    roomArea: "75",
    occupants: [],
  },
  {
    id: "LB1-F2-02",
    roomName: "Digital Archives Lab",
    capacity: 8,
    occupied: 5,
    hasSubtype: false,
    occupiedBy: "Staff",
    roomType: "Lab",
    building: "Library Block",
    floor: "second",
    status: "Partially Allocated",
    roomArea: "80",
    occupants: [],
  },
  {
    id: "SPC-G-01",
    roomName: "Main Gymnasium",
    capacity: 100,
    occupied: 60,
    hasSubtype: true,
    occupiedBy: null,
    roomType: "Gym",
    building: "Sports Complex",
    floor: "ground",
    status: "Partially Allocated",
    roomArea: "500",
    occupants: [],
  },
  {
    id: "SPC-G-02",
    roomName: "Indoor Basketball Court",
    capacity: 20,
    occupied: 10,
    hasSubtype: false,
    occupiedBy: "Sports Team",
    roomType: "Court",
    building: "Sports Complex",
    floor: "ground",
    status: "Partially Allocated",
    roomArea: "250",
    occupants: [],
  },
  {
    id: "SPC-G-03",
    roomName: "Changing Room (Male)",
    capacity: 30,
    occupied: 0,
    hasSubtype: false,
    occupiedBy: null,
    roomType: "Locker Room",
    building: "Sports Complex",
    floor: "ground",
    status: "Available",
    roomArea: "80",
    occupants: [],
  },
  {
    id: "SPC-G-04",
    roomName: "Changing Room (Female)",
    capacity: 30,
    occupied: 0,
    hasSubtype: false,
    occupiedBy: null,
    roomType: "Locker Room",
    building: "Sports Complex",
    floor: "ground",
    status: "Available",
    roomArea: "80",
    occupants: [],
  },
  {
    id: "SPC-G-05",
    roomName: "Coach's Office",
    capacity: 2,
    occupied: 2,
    hasSubtype: false,
    occupiedBy: "Coaches",
    roomType: "Office",
    building: "Sports Complex",
    floor: "ground",
    status: "Allocated",
    roomArea: "30",
    occupants: [],
  },
  {
    id: "SPC-G-06",
    roomName: "Equipment Storage",
    capacity: 5,
    occupied: 5,
    hasSubtype: false,
    occupiedBy: "Staff",
    roomType: "Storage",
    building: "Sports Complex",
    floor: "ground",
    status: "Allocated",
    roomArea: "40",
    occupants: [],
  },
  {
    id: "SPC-G-07",
    roomName: "First Aid Room",
    capacity: 2,
    occupied: 1,
    hasSubtype: false,
    occupiedBy: "Medic",
    roomType: "Medical",
    building: "Sports Complex",
    floor: "ground",
    status: "Partially Allocated",
    roomArea: "25",
    occupants: [],
  },
  {
    id: "AD0-F1-01-C1",
    roomName: "HR Manager's Cabin",
    capacity: 1,
    occupied: 1,
    hasSubtype: false,
    occupiedBy: "HR Manager",
    roomType: "Cabin",
    building: "Admin Block",
    floor: "first",
    status: "Allocated",
    roomArea: "15",
    parentId: "AD0-F1-01",
    occupants: [],
  },
  {
    id: "AD0-F1-01-C2",
    roomName: "HR Analyst Workstation 1",
    capacity: 1,
    occupied: 1,
    hasSubtype: false,
    occupiedBy: "HR Analyst 1",
    roomType: "Workstation",
    building: "Admin Block",
    floor: "first",
    status: "Allocated",
    roomArea: "10",
    parentId: "AD0-F1-01",
    occupants: [],
  },
  {
    id: "AD0-F1-01-C3",
    roomName: "HR Analyst Workstation 2",
    capacity: 1,
    occupied: 1,
    hasSubtype: false,
    occupiedBy: "HR Analyst 2",
    roomType: "Workstation",
    building: "Admin Block",
    floor: "first",
    status: "Allocated",
    roomArea: "10",
    parentId: "AD0-F1-01",
    occupants: [],
  },
  {
    id: "AD0-F1-01-MTG",
    roomName: "Internal Meeting Area",
    capacity: 6,
    occupied: 2,
    hasSubtype: false,
    occupiedBy: null,
    roomType: "Meeting Area",
    building: "Admin Block",
    floor: "first",
    status: "Partially Allocated",
    roomArea: "20",
    parentId: "AD0-F1-01",
    occupants: [],
  },
  {
    id: "AB1-G-02-WS1",
    roomName: "Workstation 1",
    capacity: 1,
    occupied: 1,
    hasSubtype: false,
    occupiedBy: "Student 1",
    roomType: "Workstation",
    building: "Academic Block 1",
    floor: "ground",
    status: "Allocated",
    roomArea: "3",
    parentId: "AB1-G-02",
    occupants: [],
  },
  {
    id: "AB1-G-02-WS2",
    roomName: "Workstation 2",
    capacity: 1,
    occupied: 1,
    hasSubtype: false,
    occupiedBy: "Student 2",
    roomType: "Workstation",
    building: "Academic Block 1",
    floor: "ground",
    status: "Allocated",
    roomArea: "3",
    parentId: "AB1-G-02",
    occupants: [],
  },
  {
    id: "AB1-G-02-WS3",
    roomName: "Workstation 3",
    capacity: 1,
    occupied: 1,
    hasSubtype: false,
    occupiedBy: "Student 3",
    roomType: "Workstation",
    building: "Academic Block 1",
    floor: "ground",
    status: "Allocated",
    roomArea: "3",
    parentId: "AB1-G-02",
    occupants: [],
  },
  {
    id: "AB2-F1-04-MA",
    roomName: "Main Meeting Area",
    capacity: 8,
    occupied: 0,
    hasSubtype: false,
    occupiedBy: null,
    roomType: "Meeting Area",
    building: "Academic Block 2",
    floor: "first",
    status: "Available",
    roomArea: "35",
    parentId: "AB2-F1-04",
    occupants: [],
  },
  {
    id: "AB2-F1-04-AV",
    roomName: "AV Console",
    capacity: 1,
    occupied: 0,
    hasSubtype: false,
    occupiedBy: null,
    roomType: "Utility",
    building: "Academic Block 2",
    floor: "first",
    status: "Available",
    roomArea: "5",
    parentId: "AB2-F1-04",
    occupants: [],
  },
  {
    id: "LB1-G-01-SC1",
    roomName: "Study Carrel 1",
    capacity: 1,
    occupied: 1,
    hasSubtype: false,
    occupiedBy: "Student",
    roomType: "Study Carrel",
    building: "Library Block",
    floor: "ground",
    status: "Allocated",
    roomArea: "2",
    parentId: "LB1-G-01",
    occupants: [],
  },
  {
    id: "LB1-G-01-SC2",
    roomName: "Study Carrel 2",
    capacity: 1,
    occupied: 1,
    hasSubtype: false,
    occupiedBy: "Student",
    roomType: "Study Carrel",
    building: "Library Block",
    floor: "ground",
    status: "Allocated",
    roomArea: "2",
    parentId: "LB1-G-01",
    occupants: [],
  },
  {
    id: "LB1-G-01-LW1",
    roomName: "Librarian Workstation 1",
    capacity: 1,
    occupied: 1,
    hasSubtype: false,
    occupiedBy: "Librarian",
    roomType: "Workstation",
    building: "Library Block",
    floor: "ground",
    status: "Allocated",
    roomArea: "5",
    parentId: "LB1-G-01",
    occupants: [],
  },
  {
    id: "AB1-G-04-SA",
    roomName: "Main Seating Area",
    capacity: 100,
    occupied: 0,
    hasSubtype: false,
    occupiedBy: null,
    roomType: "Seating Area",
    building: "Academic Block 1",
    floor: "ground",
    status: "Available",
    roomArea: "120",
    parentId: "AB1-G-04",
    occupants: [],
  },
  {
    id: "AB1-G-04-STG",
    roomName: "Stage",
    capacity: 5,
    occupied: 0,
    hasSubtype: false,
    occupiedBy: null,
    roomType: "Presentation Stage",
    building: "Academic Block 1",
    floor: "ground",
    status: "Available",
    roomArea: "20",
    parentId: "AB1-G-04",
    occupants: [],
  },
  {
    id: "AB1-G-04-CR",
    roomName: "Control Room",
    capacity: 2,
    occupied: 0,
    hasSubtype: false,
    occupiedBy: null,
    roomType: "Utility",
    building: "Academic Block 1",
    floor: "ground",
    status: "Available",
    roomArea: "10",
    parentId: "AB1-G-04",
    occupants: [],
  },
  {
    id: "SPC-G-01-WS",
    roomName: "Weights Section",
    capacity: 25,
    occupied: 20,
    hasSubtype: false,
    occupiedBy: "Students",
    roomType: "Gym Area",
    building: "Sports Complex",
    floor: "ground",
    status: "Partially Allocated",
    roomArea: "150",
    parentId: "SPC-G-01",
    occupants: [],
  },
  {
    id: "SPC-G-01-CA",
    roomName: "Cardio Area",
    capacity: 30,
    occupied: 25,
    hasSubtype: false,
    occupiedBy: "Students",
    roomType: "Gym Area",
    building: "Sports Complex",
    floor: "ground",
    status: "Partially Allocated",
    roomArea: "150",
    parentId: "SPC-G-01",
    occupants: [],
  },
  {
    id: "SPC-G-01-YC",
    roomName: "Yoga/Stretching Corner",
    capacity: 15,
    occupied: 5,
    hasSubtype: false,
    occupiedBy: "Students",
    roomType: "Workout Zone",
    building: "Sports Complex",
    floor: "ground",
    status: "Partially Allocated",
    roomArea: "50",
    parentId: "SPC-G-01",
    occupants: [],
  },
  {
    id: "SPC-G-01-MS",
    roomName: "Main Sports Hall",
    capacity: 30,
    occupied: 10,
    hasSubtype: false,
    occupiedBy: "Sports Team",
    roomType: "Court",
    building: "Sports Complex",
    floor: "ground",
    status: "Partially Allocated",
    roomArea: "150",
    parentId: "SPC-G-01",
    occupants: [],
  },
];

const Reports: Report[] = [
  {
    id: "123e4567-e89b-12d3-a456-426614174000",
    fileName: "Q3_Sales_Report.pdf",
    createdAt: "2023-10-26T10:00:00Z",
    size: "2.5 MB",
    startDate: "2023-07-01",
    endDate: "2023-09-30",
    fileUrl: "https://example.com/reports/Q3_Sales_Report.pdf",
  },
  {
    id: "123e4567-e89b-12d3-a456-426614174001",
    fileName: "Annual_Financials_2022.xlsx",
    createdAt: "2023-01-15T15:30:00Z",
    size: "5.1 MB",
    startDate: "2022-01-01",
    endDate: "2022-12-31",
    fileUrl: "https://example.com/reports/Annual_Financials_2022.xlsx",
  },
  {
    id: "123e4567-e89b-12d3-a456-426614174002",
    fileName: "Marketing_Campaign_Summary.docx",
    createdAt: "2023-11-05T09:15:00Z",
    size: "750 KB",
    startDate: "2023-10-01",
    endDate: "2023-10-31",
    fileUrl: "https://example.com/reports/Marketing_Campaign_Summary.docx",
  },
  {
    id: "2d8f9c1b-e5a1-4f6c-8b01-765f3a0029b4",
    fileName: "Employee_Directory_Q4.csv",
    createdAt: "2023-11-20T04:15:00Z",
    size: "560 KB",
    startDate: "2023-10-01",
    endDate: "2023-12-31",
    fileUrl: "https://example.com/reports/Employee_Directory_Q4.csv",
  },
  {
    id: "4a7b3c2d-9e6f-4c8e-b1a9-335c9182d4a2",
    fileName: "Project_Status_Report.pdf",
    createdAt: "2024-01-10T14:20:00Z",
    size: "1.8 MB",
    startDate: "2024-01-01",
    endDate: "2024-01-10",
    fileUrl: "https://example.com/reports/Project_Status_Report.pdf",
  },
  {
    id: "9b1c8e7d-f4a5-4b3c-8d2a-112e6945a7b3",
    fileName: "Monthly_Expenses_Jan_2024.xlsx",
    createdAt: "2025-08-14T05:34:20Z",
    size: "345 KB",
    startDate: "2024-01-01",
    endDate: "2024-01-31",
    fileUrl: "https://example.com/reports/Monthly_Expenses_Jan_2024.xlsx",
  },
];
